# Generated by Django 4.1.4 on 2023-01-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ovros_user_module', '0003_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('date_updated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(blank=True, upload_to='images/service_img')),
                ('service_price', models.CharField(max_length=20)),
                ('service_duration', models.CharField(max_length=5)),
                ('date_created', models.DateField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_user_module.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('part_type', models.CharField(max_length=50)),
                ('part_price', models.CharField(max_length=20)),
                ('service', models.ManyToManyField(through='ovros_service_module.PartForService', to='ovros_service_module.service')),
            ],
        ),
        migrations.AddField(
            model_name='partforservice',
            name='service_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_service_module.servicepart'),
        ),
        migrations.AddField(
            model_name='partforservice',
            name='servie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_service_module.service'),
        ),
    ]
