# Generated by Django 4.1.4 on 2023-01-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ovros_user_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('date_updated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(blank=True, upload_to='images/service_img')),
                ('service_description', models.CharField(blank=True, default='', max_length=500)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_duration', models.CharField(max_length=5)),
                ('is_for_car', models.BooleanField(default=False, verbose_name='Available for car')),
                ('is_for_van', models.BooleanField(default=False, verbose_name='Available for van')),
                ('is_for_suv', models.BooleanField(default=False, verbose_name='Available for suv')),
                ('is_for_lorry', models.BooleanField(default=False, verbose_name='Available for lorry')),
                ('is_for_bike', models.BooleanField(default=False, verbose_name='Available for bike')),
                ('service_availability', models.BooleanField(default=False, help_text='is service available currently', verbose_name='Service availability')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_user_module.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('part_type', models.CharField(max_length=50)),
                ('part_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ManyToManyField(through='ovros_service_module.PartForService', to='ovros_service_module.service')),
            ],
        ),
        migrations.AddField(
            model_name='partforservice',
            name='service_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_service_module.servicepart'),
        ),
        migrations.AddField(
            model_name='partforservice',
            name='servie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_service_module.service'),
        ),
    ]
