# Generated by Django 4.1.4 on 2023-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_service_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
