# Generated by Django 4.1.4 on 2023-01-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_service_module', '0002_service_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
