# Generated by Django 4.1.4 on 2023-01-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_service_module', '0003_alter_service_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicepart',
            name='part_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
