# Generated by Django 4.1.4 on 2023-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_service_module', '0004_service_service_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_availability',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepart',
            name='part_price',
            field=models.CharField(max_length=20),
        ),
    ]
