# Generated by Django 4.1.4 on 2022-12-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ovros_user_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('USER_ADMIN', 'UserAdmin'), ('USER_SHOP', 'UserShop'), ('USER_SHOP_MEMBER', 'UserShopMember'), ('USER_CUSTOMER', 'UserCustomer')], default='USER_SHOP', max_length=40, verbose_name='Type')),
                ('shop_name', models.CharField(help_text='Service Shop name', max_length=100)),
                ('shop_address', models.CharField(help_text='Service Shop address', max_length=200)),
                ('shop_contact', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Name of your Bank', max_length=100)),
                ('bank_account_no', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('user_role', models.CharField(choices=[('USER_ADMIN', 'UserAdmin'), ('USER_SHOP', 'UserShop'), ('USER_SHOP_MEMBER', 'UserShopMember'), ('USER_CUSTOMER', 'UserCustomer')], default='USER_CUSTOMER', max_length=40, verbose_name='Type')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
