# Generated by Django 4.1.4 on 2023-02-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_user_module', '0002_remove_shopprofile_shop_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_contact',
            field=models.CharField(help_text='eg: 07xxxxxxxx', max_length=10),
        ),
    ]
