# Generated by Django 4.1.4 on 2022-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_user_module', '0002_shopprofile_userbankdetails_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
