# Generated by Django 4.1.4 on 2023-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_user_module', '0003_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
