# Generated by Django 4.1.4 on 2023-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_user_module', '0004_alter_shopprofile_shop_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_address_city',
            field=models.CharField(choices=[('SelectDistrict', 'Select District'), ('Colombo', 'Colombo')], help_text='Service Shop address city', max_length=200),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_address_district',
            field=models.CharField(choices=[('SelectCity', 'Select City'), ('Colombo 01', 'Colombo 01'), ('Colombo 02', 'Colombo 02'), ('Colombo 03', 'Colombo 03'), ('Colombo 04', 'Colombo 04'), ('Colombo 05', 'Colombo 05'), ('Colombo 06', 'Colombo 06'), ('Colombo 07', 'Colombo 07'), ('Colombo 08', 'Colombo 08'), ('Colombo 09', 'Colombo 09'), ('Colombo 10', 'Colombo 10'), ('Colombo 11', 'Colombo 11'), ('Colombo 12', 'Colombo 12'), ('Colombo 13', 'Colombo 13'), ('Colombo 14', 'Colombo 14'), ('Colombo 15', 'Colombo 15'), ('Dehiwala', 'Dehiwala'), ('Homagama', 'Homagama'), ('Kaduwela', 'Kaduwela'), ('Kesbewa', 'Kesbewa'), ('Kolonnawa', 'Kolonnawa'), ('Kotte', 'Kotte'), ('Maharagama', 'Maharagama'), ('Moratuwa', 'Moratuwa'), ('Padukka', 'Padukka'), ('Ratmalana', 'Ratmalana'), ('Seethawaka', 'Seethawaka'), ('Thimbirigasyaya', 'Thimbirigasyaya')], help_text='Service Shop address district', max_length=200),
        ),
    ]
