# Generated by Django 4.1.4 on 2023-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_user_module', '0005_alter_shopprofile_shop_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_address_no',
            field=models.CharField(help_text='Service Shop address Number', max_length=200),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_address_street',
            field=models.CharField(help_text='Service Shop address street', max_length=200),
        ),
    ]
