# Generated by Django 4.1.4 on 2023-01-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ovros_user_module', '0004_userprofile_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Name of your Bank', max_length=100)),
                ('bank_branch', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('shop_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ovros_user_module.shopprofile')),
            ],
        ),
    ]
