# Generated by Django 4.1.4 on 2023-01-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_payment_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppaymentdetail',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
