# Generated by Django 4.1.4 on 2023-01-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ovros_user_module', '0004_userprofile_contact_number'),
        ('ovros_service_module', '0003_alter_service_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_note', models.CharField(blank=True, max_length=250)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_service_module.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_user_module.userprofile')),
            ],
        ),
    ]
