# Generated by Django 4.1.4 on 2023-01-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ovros_user_module', '0001_initial'),
        ('ovros_service_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('vehicle', models.CharField(choices=[('NON', 'Non'), ('CAR', 'Car'), ('VAN', 'Van'), ('BIKE', 'Bike'), ('SUV', 'Suv')], default='NON', max_length=5)),
                ('booking_note', models.CharField(blank=True, max_length=250)),
                ('booking_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=10)),
                ('service_status', models.CharField(choices=[('PENDING', 'PENDING'), ('QUEUED', 'QUEUED'), ('ONGOING', 'ONGOING'), ('OVER', 'OVER')], default='PENDING', max_length=30)),
                ('payment_status', models.CharField(choices=[('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAYMENT_COMPLETED', 'PAYMENT_COMPLETED')], default='PAYMENT_PENDING', max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_service_module.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovros_user_module.userprofile')),
            ],
        ),
    ]
