# Generated by Django 4.1.4 on 2023-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='vehicle',
            field=models.CharField(choices=[('NON', 'Non'), ('CAR', 'Car'), ('VAN', 'Van'), ('BIKE', 'Bike'), ('SUV', 'Suv')], default='NON', max_length=5),
        ),
    ]
