# Generated by Django 4.1.4 on 2023-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
    ]
