# Generated by Django 4.1.4 on 2023-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_booking', '0002_servicebooking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=10),
        ),
    ]
