# Generated by Django 4.1.4 on 2023-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovros_booking', '0003_servicebooking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAYMENT_COMPLETED', 'PAYMENT_COMPLETED')], default='PAYMENT_PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('QUEUED', 'QUEUED'), ('ONGOING', 'ONGOING'), ('OVER', 'OVER')], default='PENDING', max_length=30),
        ),
    ]
